### ISSUE TITLE
INT2 - out of bounds. All integer data types create the yaml spec

### ISSUE THREAD

**Issue by data-matt** [fabiog1901/dbworkload#4]
Hey, 

It seems all integer datatypes create the same yaml spec.

`"type": "integer",
                "args": {
                    "min": 0,
                    "max": 1000000,
                    "seed": random.random(),
                    "null_pct": (
                        0.0
                        if is_not_null
                        else round(random.randint(NOT_NULL_MIN, NOT_NULL_MAX) / 100, 2)
                    ),
                    "array": DEFAULT_ARRAY_COUNT if is_array else 0,
                },`

For INT2 this definitely needs to create ints between  -32768 to +32767

Thanks,
Matt

**Comment by data-matt** [comment]
https://github.com/fabiog1901/dbworkload/blob/main/dbworkload/utils/common.py#L362

**Comment by fabiog1901** [comment]
fixed with commit [4c67a9f](https://github.com/fabiog1901/dbworkload/commit/4c67a9f0f2b731e06a006bf2b75e320a10df00a6), it will be part of next patch release v0.2.2
